### ISSUE TITLE
Framework name change

### ISSUE THREAD

**Issue by tigaszzz** [ircmaxell/Pila-PHP#2]
Hi,

as a Portuguese developer the name of your framework is to say the least... funny...

in Portuguese Pila stands for Dick/Cock in English ;)

you can look at it at http://www.youswear.com/index.asp?word=pila#.Vz8jvZMrJE4

**Comment by gabidavila** [comment]
That's for PT-PT, on PT-BR it doesn't mean that. Except if you use "Pica".

**Comment by ircmaxell** [comment]
Name Changed to Tari-PHP
